#!/usr/bin/bash

DOMAIN=$1
PORT=$2

# date_time=$(date +%m-%d-%Y_%H:%M:%S)

sudo nmap $DOMAIN -p- -A -O -T3 -v3 -oN nmap_output_%m-%d-%Y_%H-%M-%S_$1_.txt | tee nmap_output_$(date +%m-%d-%Y_%H-%M-%S)_$1_.bak

# sudo nmap $DOMAIN -p$PORT -sV -A -O -v3 -oN nmap_output_%m-%d-%Y_%H-%M-%S_$1_.txt | tee nmap_output_$(date +%m-%d-%Y_%H-%M-%S)_$1_.bak
